services:
  - type: web
    name: saas-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "postgresql://postgres:[YOUR-PASSWORD]@db.[PROJECT-REF].supabase.co:5432/postgres"
      - key: JWT_SECRET
        value: "your-super-secret-jwt-key-here-make-it-very-long-and-random"
      - key: PORT
        value: 10000
