services:
  - type: web
    name: saas-school-management-v2
    env: node
    plan: free
    nodeVersion: 18
    buildCommand: "npm install && npm run build && cd backend && node setup-database.js"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: "production"
      - key: DATABASE_URL
        value: "file:./dev.db"
      - key: JWT_SECRET
        value: "8e6df3fda7688e47b15bc20bcf681c9845be8178e217555c4a7b0d19b315de39930e7e05120bef3dea4023c8b6899fb97f8548961313def71bd5afb3c6ac4cd0"
      - key: PORT
        value: "10000"
